dataset:
  _target_: "nemo.collections.tts.data.dataset.VocoderDataset"
  manifest_filepath: ${validation_datasets}
  sample_rate: ${sample_rate}
  n_segments: ${val_n_segments}
  max_duration: ${val_max_duration}
  min_duration: ${val_min_duration}
dataloader_params:
  drop_last: false
  shuffle: false
  batch_size: 16
  num_workers: 1
  pin_memory: true
