dataset:
  _target_: "nemo.collections.tts.data.dataset.VocoderDataset"
  manifest_filepath: ${train_dataset}
  sample_rate: ${sample_rate}
  n_segments: ${train_n_segments}
  max_duration: ${train_max_duration}
  min_duration: ${train_min_duration}
  load_precomputed_mel: true
  hop_length: ${n_window_stride}
dataloader_params:
  drop_last: false
  shuffle: true
  batch_size: 16
  num_workers: 4
  pin_memory: true
