name: stable-diffusion-train

fid:
  classifier_free_guidance:
    - 1.5
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  nnodes_per_cfg: 1
  ntasks_per_node: 8
  local_task_id: null
  num_images_to_eval: 30000
  coco_captions_path: /coco2014/coco2014_val_sampled_30k/captions
  coco_images_path: /coco2014/coco2014_val/images_256
  save_path: output

infer:
  unconditional_guidance_scale: null
  num_images_per_prompt: 1
  height: 512
  width: 512
  down_factor: 8
  inference_steps: 50
  sampler_type: 'PLMS'
  eta: 0
  output_type: 'pil'
  save_to_file: False # We need to rename and maintain the order of images for clip score calculation, so we will save it outside the inference pipeline
  out_path: ${fid.save_path}
  seed: 123
  prompts:
  batch_size: 8

trainer:
  devices: ${fid.ntasks_per_node}
  num_nodes: 1
  accelerator: gpu
  precision: 32
  logger: False # logger provided by exp_manager

model:
  restore_from_path: null
  precision: ${trainer.precision}
