name: stable-diffusion-train

infer:
  unconditional_guidance_scale: 7.5
  num_images_per_prompt: 4
  batch_size: 8
  height: 512
  width: 512
  down_factor: 8
  inference_steps: 25
  sampler_type: 'DPM'
  eta: 0
  output_type: 'pil'
  save_to_file: True
  out_path: 'stable-diffusion'
  seed: 123
  prompts:
    - 'A photo of a Shiba Inu dog with a backpack riding a bike. It is wearing sunglasses and a beach hat.'
    - 'A cute corgi lives in a house made out of sushi.'
    - 'A high contrast portrait of a very happy fuzzy panda dressed as a chef in a high end kitchen making dough. There is a painting of flowers on the wall behind him.'
    - 'A brain riding a rocketship heading towards the moon.'

trainer:
  devices: 1
  num_nodes: 1
  accelerator: gpu
  precision: 16
  logger: False # logger provided by exp_manager

model:
  restore_from_path: null
  precision: ${trainer.precision}
